Pizza=("pizza","chicken Pizza",6,"large")
Burger=("burger,cheese byrger",4,"spicy,large")
print("burger details:",Burger)
print("Pizza details:",Pizza)
print("first value of pizza",Pizza[0])
print("first value of pizza",Pizza[1])
print("First vale of pizza",Pizza[2])
print("first value of pizza",Pizza[-1])
print("first value of Burger",Burger[0])
print("first value of Burger",Burger[1])
print("First vale of Burger",Burger[2])
print("first value of Burger",Burger[-1])

all_recipes = (Pizza,Burger)
print("First recipe name:",all_recipes[0][0])
print("second recipe time",all_recipes[1][2],"mins")
print("pasta details (sliced):",Pizza[1:3])
