file=open("Rasingan.txt","w")
file.write("I am Minato Namikaze")
file.close()

file=open("Rasingan.txt","r")
content=file.read()
print(content)
file.close()
file=open("Rasingan.txt","r")
lines=file.readlines()
print(f"You have {len(lines)} items on your Rasingan list.")
file.close()
file=open("Rasingan.txt","a")
file.write("4.Travel to Japan\n")
file.write("5. Run a 5K marathon\n")
file.close()
print("\n2 more items added")
file=open("Rasingan.txt","r")
print("\n===Updated Rasingan===")
print(file.read())
file.close()