n=int(input("Enter a number(try 5 or 12): "))
guess=int(input("Guess its binary: "))
input("Binary. Press enter ")
print(" decimal",n, "-> binary", bin(n)[2:])
print("Your guess :", guess)
input("AND - both bits must be 1. Press Enter :")
print(" 12 =",bin(12)[2:])
print(" 10  =",bin(10)[2:])
print(" 12 & 10 =",bin(12 & 10)[2:])
input("OR - at least one not must be 1. Press Enter ")
print(" 12 | 10 =", 12 | 10)
