n =int(input("Enter a number(try 5 or 12): "))
guess =input("Left shift doubles it. Guess: "+ str(n) +" << 1 = ")
input("NOT - flips the bits. Press enter ")
print(" 12 =",bin(12)[2:])
print(" NOT 12 =",~12 & 0xFF)
input("XOR - differnet bits give 1. Press Enter ")
print(" 12 ^ 10 =", 12 ^ 10)
input("Left shift - multiples by 2. Press Enter ")
print("   ", n,">> 1 =" ,n >> 1)
